# LSTM Autoencoder for Anamoly Detection

## Import Dependencies

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

import tensorflow as tf
from keras.models import Sequential
from keras.layers import LSTM, RepeatVector, TimeDistributed, Dense

Using TensorFlow backend.


### We will try to recreate the sequence [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] using LSTM Autoencoder Structure

## Define Input Sequences 

In [2]:
input_sequence = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ])

### For an LSTM Autoencoder the shape of input has to be of the format 
### Size of Input Data  is n_samples * timesteps * n_features 

In [3]:
# Reshape the input
n = len(input_sequence)
print(n)
reshaped_input_sequence = input_sequence.reshape((1, n, 1))
reshaped_input_sequence

10


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

### Now we have the input shape defined we need to design our encoder - decoder structure. To Define in basic terms an Autoencoder works in this way it takes an input sample, extracts all the important information (called as latent variable) , which also helps in elimanting noise and reconstructs back the input at the output with the help of the latent variable. 

## Design of LSTM Autoencoder Architecture

In [4]:
model = Sequential()

# Encoder Stage
model.add(LSTM(100, activation = "relu", input_shape = (n, 1)))

model.add(RepeatVector(n))

# Decoder Stage
model.add(LSTM(100, activation = "relu",return_sequences = True))

model.add(TimeDistributed(Dense(1)))

model.compile(optimizer = "adam", loss = "mse")
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 100)               40800     
_________________________________________________________________
repeat_vector_1 (RepeatVecto (None, 10, 100)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 10, 100)           80400     
_________________________________________________________________
time_distributed_1 (TimeDist (None, 10, 1)             101       
Total params: 121,301
Trainable params: 121,301
Non-trainable params: 0
_________________________________________________________________


## Train the model
### Here it is important to understand the input and output to the model has to be same sequence so that the model can learn to understand the "MOST" important features of the Input


In [5]:
model.fit(reshaped_input_sequence, reshaped_input_sequence, epochs = 500, verbose = 1)

Epoch 1/500
1/1 [==============================] - 1s 560ms/step - loss: 40.7458
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 39.1590
Epoch 3/500
1/1 [==============================] - 0s 9ms/step - loss: 37.1752
Epoch 4/500
1/1 [==============================] - 0s 10ms/step - loss: 35.4327
Epoch 5/500
1/1 [==============================] - 0s 10ms/step - loss: 33.6628
Epoch 6/500
1/1 [==============================] - 0s 12ms/step - loss: 31.8016
Epoch 7/500
1/1 [==============================] - 0s 9ms/step - loss: 29.7467
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 27.3026
Epoch 9/500
1/1 [==============================] - 0s 12ms/step - loss: 24.3895
Epoch 10/500
1/1 [==============================] - 0s 11ms/step - loss: 20.7004
Epoch 11/500
1/1 [==============================] - 0s 8ms/step - loss: 15.9501
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 9.8807
Epoch 13/500
1/1 [========================

Epoch 104/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9167e-04
Epoch 105/500
1/1 [==============================] - 0s 7ms/step - loss: 5.0842e-04
Epoch 106/500
1/1 [==============================] - 0s 7ms/step - loss: 5.4048e-04
Epoch 107/500
1/1 [==============================] - 0s 6ms/step - loss: 3.7548e-04
Epoch 108/500
1/1 [==============================] - 0s 8ms/step - loss: 1.7033e-04
Epoch 109/500
1/1 [==============================] - 0s 7ms/step - loss: 9.0568e-05
Epoch 110/500
1/1 [==============================] - 0s 7ms/step - loss: 1.6811e-04
Epoch 111/500
1/1 [==============================] - 0s 8ms/step - loss: 2.9526e-04
Epoch 112/500
1/1 [==============================] - 0s 8ms/step - loss: 3.4075e-04
Epoch 113/500
1/1 [==============================] - 0s 8ms/step - loss: 2.6851e-04
Epoch 114/500
1/1 [==============================] - 0s 8ms/step - loss: 1.5281e-04
Epoch 115/500
1/1 [==============================] - 0s 8ms/step - loss: 9.3

Epoch 202/500
1/1 [==============================] - 0s 7ms/step - loss: 4.4417e-05
Epoch 203/500
1/1 [==============================] - 0s 7ms/step - loss: 4.4200e-05
Epoch 204/500
1/1 [==============================] - 0s 8ms/step - loss: 4.3972e-05
Epoch 205/500
1/1 [==============================] - 0s 7ms/step - loss: 4.3757e-05
Epoch 206/500
1/1 [==============================] - 0s 7ms/step - loss: 4.3553e-05
Epoch 207/500
1/1 [==============================] - 0s 7ms/step - loss: 4.3349e-05
Epoch 208/500
1/1 [==============================] - 0s 7ms/step - loss: 4.3142e-05
Epoch 209/500
1/1 [==============================] - 0s 7ms/step - loss: 4.2933e-05
Epoch 210/500
1/1 [==============================] - 0s 7ms/step - loss: 4.2723e-05
Epoch 211/500
1/1 [==============================] - 0s 7ms/step - loss: 4.2523e-05
Epoch 212/500
1/1 [==============================] - 0s 7ms/step - loss: 4.2329e-05
Epoch 213/500
1/1 [==============================] - 0s 7ms/step - loss: 4.2

Epoch 300/500
1/1 [==============================] - 0s 7ms/step - loss: 3.0032e-05
Epoch 301/500
1/1 [==============================] - 0s 8ms/step - loss: 2.9936e-05
Epoch 302/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9838e-05
Epoch 303/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9739e-05
Epoch 304/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9644e-05
Epoch 305/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9545e-05
Epoch 306/500
1/1 [==============================] - 0s 6ms/step - loss: 2.9450e-05
Epoch 307/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9355e-05
Epoch 308/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9260e-05
Epoch 309/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9166e-05
Epoch 310/500
1/1 [==============================] - 0s 7ms/step - loss: 2.9073e-05
Epoch 311/500
1/1 [==============================] - 0s 8ms/step - loss: 2.8

Epoch 398/500
1/1 [==============================] - 0s 8ms/step - loss: 2.2218e-05
Epoch 399/500
1/1 [==============================] - 0s 7ms/step - loss: 2.2152e-05
Epoch 400/500
1/1 [==============================] - 0s 8ms/step - loss: 2.2084e-05
Epoch 401/500
1/1 [==============================] - 0s 8ms/step - loss: 2.2018e-05
Epoch 402/500
1/1 [==============================] - 0s 7ms/step - loss: 2.1953e-05
Epoch 403/500
1/1 [==============================] - 0s 8ms/step - loss: 2.1885e-05
Epoch 404/500
1/1 [==============================] - 0s 7ms/step - loss: 2.1820e-05
Epoch 405/500
1/1 [==============================] - 0s 9ms/step - loss: 2.1754e-05
Epoch 406/500
1/1 [==============================] - 0s 7ms/step - loss: 2.1688e-05
Epoch 407/500
1/1 [==============================] - 0s 10ms/step - loss: 2.1624e-05
Epoch 408/500
1/1 [==============================] - 0s 7ms/step - loss: 2.1559e-05
Epoch 409/500
1/1 [==============================] - 0s 10ms/step - loss: 2

Epoch 496/500
1/1 [==============================] - 0s 10ms/step - loss: 1.6420e-05
Epoch 497/500
1/1 [==============================] - 0s 9ms/step - loss: 1.6369e-05
Epoch 498/500
1/1 [==============================] - 0s 7ms/step - loss: 1.6317e-05
Epoch 499/500
1/1 [==============================] - 0s 10ms/step - loss: 1.6264e-05
Epoch 500/500
1/1 [==============================] - 0s 7ms/step - loss: 1.6213e-05


# Test the Model
### Let us first test the model with same input sequence

In [6]:
y_pred = model.predict(reshaped_input_sequence, verbose =0)
y_pred

array([[[1.0098003],
        [2.002984 ],
        [2.999517 ],
        [3.9977894],
        [4.997105 ],
        [5.9976077],
        [6.9999084],
        [8.002509 ],
        [9.004386 ],
        [9.9965515]]], dtype=float32)

In [8]:
import sklearn
from sklearn.metrics import mean_squared_error

In [9]:
y_true = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y_pred=y_pred.reshape(10,1)

print("MSE : " , mean_squared_error(y_true, y_pred))


MSE :  1.6160689200717114e-05


## MSE of Output with Input is very low i.e. NO ANOMALY

## The model is able to recreate the input with some error. Let us give a completely new sequence and check the output

In [10]:
y_true = [0.9,1.9,2.9,3.9,4.9,6.2,7.3,8.4,9.2,10]
test_sequence = np.array([0.9,1.9,2.9,3.9,4.9,6.2,7.3,8.4,9.2,10])
n = len(test_sequence)
reshaped_test_sequence = test_sequence.reshape((1, n, 1))

y_pred = model.predict(reshaped_test_sequence, verbose =0)
y_pred=y_pred.reshape(10,1)

print("MSE : " , mean_squared_error(y_true, y_pred))

MSE :  0.02904303945489961


## The MSE is low as the Output is a close approximation with the Input

In [11]:
test_sequence = np.array([0.4,1.0,2.9,3.9,4.1,5.4,6.5,7.8,8.9,9.7])

n = len(test_sequence)
reshaped_test_sequence = test_sequence.reshape((1, n, 1))

y_pred = model.predict(reshaped_test_sequence, verbose =0)
y_pred

array([[[0.91362953],
        [1.8004426 ],
        [2.6818688 ],
        [3.5573835 ],
        [4.427542  ],
        [5.2932734 ],
        [6.156685  ],
        [7.01968   ],
        [7.8823814 ],
        [8.742325  ]]], dtype=float32)

In [12]:
y_true = [0.4,1.0,2.9,3.9,4.1,5.4,6.5,7.8,8.9,9.7]
y_pred=y_pred.reshape(10,1)
mean_squared_error(y_true, y_pred)

0.3867619143661493

## The MSE is high i.e. the Input in this case is something the model has not seen, Hence ANOMALY